/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package uiAdmin;

import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import model.Encounter;
import model.EncounterHistory;
import model.Patient;
import model.Person;
import model.VitalSigns;
import model.*;

/**
 *
 * @author krishnamayavat
 */
public class AddVitalsJPanel extends javax.swing.JPanel {

     private JPanel userProcessContainer;
     EncounterHistory encHistory;
    
     VitalSigns vital;
     Person p;
   
    public AddVitalsJPanel(JPanel upc, VitalSigns v, Person p) {
        initComponents();
        userProcessContainer = upc;
       
        encHistory= new EncounterHistory();
       this.p = p;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtheartrate = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtbp = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtwt = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtheight = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtbodytemp = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel1.setText("Add Vital Signs");

        jLabel2.setText("Heart Rate :");

        jLabel3.setText("Blood Pressure :");

        jLabel4.setText("Weight:");

        jLabel5.setText("Height:");

        jLabel6.setText("Body Temperature:");

        jButton1.setText("Add");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("<< back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 101, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(215, 215, 215))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(148, 148, 148)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5))
                        .addGap(65, 65, 65)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtheartrate, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtbp, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtwt, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtheight, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtbodytemp, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(303, 303, 303)
                        .addComponent(jButton1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jButton2)))
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtheartrate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(txtbp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(txtwt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtheight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtbodytemp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(43, 43, 43))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
           userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
          System.out.println("----add-----"+this.p.getHealthid());
         if(txtheartrate.getText().isEmpty()||txtbp.getText().isEmpty()||txtwt.getText().isEmpty()||txtheight.getText().isEmpty()||txtbodytemp.getText().isEmpty())

         {
         
            JOptionPane.showMessageDialog(this, "Please enter details ","Error",JOptionPane.ERROR_MESSAGE); 
         
         }
         
         else if(!txtheartrate.getText().matches("[0-9]{1,13}(\\.[0-9]*)?"))
         
         {
              JOptionPane.showMessageDialog(this, "Please enter Heart Rate in the correct format  ","Error",JOptionPane.ERROR_MESSAGE); 
         
         }
         
         
          else if(!txtbp.getText().matches("[0-9]{1,13}(\\.[0-9]*)?"))
         
         {
              JOptionPane.showMessageDialog(this, "Please enter Blood pressure in the correct format  ","Error",JOptionPane.ERROR_MESSAGE); 
         
         }
         
          else if(!txtwt.getText().matches("^\\d{3}$"))
         
         {
              JOptionPane.showMessageDialog(this, "Please enter Weight in the correct format  ","Error",JOptionPane.ERROR_MESSAGE); 
         
         }
         
         
          else if(!txtheight.getText().matches("^\\d{1,3}$"))
         
         {
              JOptionPane.showMessageDialog(this, "Please enter height in the correct format  ","Error",JOptionPane.ERROR_MESSAGE); 
         
         }
         
          else if(!txtbodytemp.getText().matches("^\\d{1,3}$"))
         
         {
              JOptionPane.showMessageDialog(this, "Please enter Temperature in the correct format  ","Error",JOptionPane.ERROR_MESSAGE); 
         
         }
         
          else {
          
           Double heartrate = Double.parseDouble(txtheartrate.getText());
            Double bp = Double.parseDouble(txtbp.getText());
               Double wt = Double.parseDouble(txtwt.getText());
               Double height = Double.parseDouble(txtheight.getText());
                   Double temp = Double.parseDouble(txtbodytemp.getText());
              
                
                   encHistory.addEncounterHistory(heartrate,bp,wt,height,temp);
                   
//                   System.out.println("----history---"+encHistory.getHistory());
                    JOptionPane.showMessageDialog(this, "Information saved");
                    
                
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);   
        
        PersonDirectory pd = new PersonDirectory();
         
         


        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField txtbodytemp;
    private javax.swing.JTextField txtbp;
    private javax.swing.JTextField txtheartrate;
    private javax.swing.JTextField txtheight;
    private javax.swing.JTextField txtwt;
    // End of variables declaration//GEN-END:variables

    
}
