/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package uiAdmin;

import java.awt.CardLayout;
import javax.swing.JPanel;
import model.PatientDirectory;
import model.PersonDirectory;

/**
 *
 * @author krishnamayavat
 */
public class AdminWorkJPanel extends javax.swing.JPanel {

     private JPanel userProcessContainer;
     PersonDirectory personDirectory; 
     PatientDirectory patientDirectory;
    
    public AdminWorkJPanel(JPanel userProcessContainer,PersonDirectory personDirectory) {
        initComponents();
        
        this.userProcessContainer=userProcessContainer;
        this.personDirectory=personDirectory;
    }

     
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbltitle = new javax.swing.JLabel();
        btnmanagepersons = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        btnmanagepatient = new javax.swing.JButton();

        lbltitle.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        lbltitle.setText("                          Administrator's Work Panel");

        btnmanagepersons.setText("Manage Persons");
        btnmanagepersons.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmanagepersonsActionPerformed(evt);
            }
        });

        jButton1.setText("View Abnormal Cases");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btnmanagepatient.setText("Manage Patient");
        btnmanagepatient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmanagepatientActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lbltitle, javax.swing.GroupLayout.PREFERRED_SIZE, 469, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(145, 145, 145))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnmanagepatient, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnmanagepersons, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1))
                        .addGap(181, 181, 181))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(lbltitle, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(83, 83, 83)
                .addComponent(btnmanagepersons)
                .addGap(18, 18, 18)
                .addComponent(btnmanagepatient)
                .addGap(26, 26, 26)
                .addComponent(jButton1)
                .addContainerGap(123, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnmanagepersonsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmanagepersonsActionPerformed

    ManagePersonsJPanel ms = new ManagePersonsJPanel(userProcessContainer, personDirectory);
    userProcessContainer.add("ManagePersonsJPanel", ms);
    CardLayout layout = (CardLayout) userProcessContainer.getLayout();
    layout.next(userProcessContainer);

    }//GEN-LAST:event_btnmanagepersonsActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

      AbnormalJPanel ajp = new AbnormalJPanel(userProcessContainer, personDirectory);
    userProcessContainer.add("ManagePersonsJPanel", ajp);
    CardLayout layout = (CardLayout) userProcessContainer.getLayout();
    layout.next(userProcessContainer);



        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnmanagepatientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmanagepatientActionPerformed
         
          ManagePatientJPanel ms = new ManagePatientJPanel(userProcessContainer, personDirectory);
    userProcessContainer.add("ManagePersonsJPanel", ms);
    CardLayout layout = (CardLayout) userProcessContainer.getLayout();
    layout.next(userProcessContainer);

        


        // TODO add your handling code here:
    }//GEN-LAST:event_btnmanagepatientActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnmanagepatient;
    private javax.swing.JButton btnmanagepersons;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel lbltitle;
    // End of variables declaration//GEN-END:variables
}
