/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package uiAdmin;

import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import model.Encounter;
import model.EncounterHistory;
import model.Patient;
import model.PatientDirectory;
import model.Person;
import model.PersonDirectory;

/**
 *
 * @author krishnamayavat
 */
public class ManagePatientJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private PersonDirectory personDirectory;
   private Encounter encounter;
   private EncounterHistory encHistory;
   private Patient patient;
   private PatientDirectory patientDirectory;

   
    public ManagePatientJPanel(JPanel upc, PersonDirectory pd) {
        initComponents();
        userProcessContainer = upc;
        personDirectory = pd;
        populateTable();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnencountervital = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        mp1table = new javax.swing.JTable();
        btnback = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnencountervital1 = new javax.swing.JButton();

        btnencountervital.setText("Manage Encounter/Vitals");
        btnencountervital.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnencountervitalActionPerformed(evt);
            }
        });

        mp1table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "HealthID", "Name", "Age", "City", "Community", "House", "Zipcode"
            }
        ));
        jScrollPane1.setViewportView(mp1table);

        btnback.setText("<< back");
        btnback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbackActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel1.setText("Manage Patient");

        btnencountervital1.setText("Manage Encounter/Vitals");
        btnencountervital1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnencountervital1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(btnback)
                        .addGap(95, 95, 95)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 187, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(190, 190, 190)
                .addComponent(btnencountervital1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnback)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnencountervital1)
                .addContainerGap(181, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbackActionPerformed

        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);

        // TODO add your handling code here:
    }//GEN-LAST:event_btnbackActionPerformed

    private void btnencountervitalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnencountervitalActionPerformed

        ManageEncounterJPanel ms = new ManageEncounterJPanel(userProcessContainer, encHistory);
        userProcessContainer.add("Administrative", ms);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnencountervitalActionPerformed

    private void btnencountervital1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnencountervital1ActionPerformed

          int row = mp1table.getSelectedRow();
////                int selectedRowIndex = mp1table.getSelectedRow();
//        Person ps = (Person) mp1table.getValueAt(row, 0);
//
////           Person ps = (Person) mptable.getValueAt(selectedRowIndex, 0);
//
//          System.out.println("---row-----"+row+"----"+ps);
        if(row<0){
            JOptionPane.showMessageDialog(null, "Please select a row!!", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        Person p = (Person)mp1table.getValueAt(row,0);
        ManageEncounterJPanel vs = new ManageEncounterJPanel(userProcessContainer, p);
        userProcessContainer.add("View", vs);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnencountervital1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnback;
    private javax.swing.JButton btnencountervital;
    private javax.swing.JButton btnencountervital1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable mp1table;
    // End of variables declaration//GEN-END:variables

    
     public void populateTable() {

         
    DefaultTableModel model= (DefaultTableModel) mp1table.getModel();
        model.setRowCount(0);
        
       System.out.println("-----table----");
        for(Person p : personDirectory.getPersonlist())
        {
             if(p.isPatientb()==true)
             {
            Object[] row=new Object[8];
            row[0]=p;
            row[1]=p.getHealthid();
            row[2]=p.getAge();
            row[3]=p.getCity();
            row[4]=p.getCommunity();
            row[5]=p.getHouse();
            row[6]=p.getZipcode();
          
            model.addRow(row);
        }
        

        }
    }

  
}
