/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package uiAdmin;

import java.awt.CardLayout;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import model.Encounter;
import model.EncounterHistory;
import model.Patient;
import model.PatientDirectory;
import model.Person;
import model.VitalSigns;

/**
 *
 * @author krishnamayavat
 */
public class ManageEncounterJPanel extends javax.swing.JPanel {

   
     
     private JPanel userProcessContainer;
     Encounter encounter;
     VitalSigns vital;
     Person person;
     Patient patient;
     PatientDirectory patientDirectory;
     EncounterHistory encHistory;
     
    
    
    public ManageEncounterJPanel(JPanel upc, EncounterHistory e) {
        initComponents();
        userProcessContainer = upc;
        encHistory = e;
        populateEncounterTable();
    }
    
    
    
    public ManageEncounterJPanel(JPanel upc, Person p) {
        initComponents();
        userProcessContainer = upc;
        person = p;
    }

  
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        btnView = new javax.swing.JButton();
        btnCreate = new javax.swing.JButton();
        btnvital = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        lblhealth = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        encounterusertable = new javax.swing.JTable();
        btnSearch1 = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(300, 398));
        setLayout(null);

        lblTitle.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblTitle.setText("Manage Encounter Details");
        add(lblTitle);
        lblTitle.setBounds(237, 25, 204, 22);

        btnView.setText("View Details");
        btnView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewActionPerformed(evt);
            }
        });
        add(btnView);
        btnView.setBounds(220, 320, 143, 29);

        btnCreate.setText("New Encounter..");
        btnCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateActionPerformed(evt);
            }
        });
        add(btnCreate);
        btnCreate.setBounds(10, 270, 146, 29);

        btnvital.setText("View Vitals");
        btnvital.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnvitalActionPerformed(evt);
            }
        });
        add(btnvital);
        btnvital.setBounds(160, 270, 130, 29);

        btnBack.setText("<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack);
        btnBack.setBounds(29, 25, 110, 29);

        btnDelete.setText("Delete ");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        add(btnDelete);
        btnDelete.setBounds(430, 270, 144, 29);

        lblhealth.setText("HelathID:");
        add(lblhealth);
        lblhealth.setBounds(29, 72, 59, 16);

        encounterusertable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "LastVisitDate", "Encounter No.", "HealthID"
            }
        ));
        jScrollPane1.setViewportView(encounterusertable);

        add(jScrollPane1);
        jScrollPane1.setBounds(29, 100, 523, 150);

        btnSearch1.setText("Add Vitals");
        btnSearch1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearch1ActionPerformed(evt);
            }
        });
        add(btnSearch1);
        btnSearch1.setBounds(290, 270, 130, 29);
    }// </editor-fold>//GEN-END:initComponents

    private void btnViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewActionPerformed

        ViewEncounterJPanel_1 vejp = new ViewEncounterJPanel_1(userProcessContainer, encounter);
        userProcessContainer.add("AddEncounterJPanel", vejp);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
        
    }//GEN-LAST:event_btnViewActionPerformed

    private void btnCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateActionPerformed

        AddEncounterJPanel aejp = new AddEncounterJPanel(userProcessContainer, encHistory);
        userProcessContainer.add("AddEncounterJPanel", aejp);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
      
    }//GEN-LAST:event_btnCreateActionPerformed

    private void btnvitalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnvitalActionPerformed
       
       ViewVitalsUserJPanel vvjp = new ViewVitalsUserJPanel(userProcessContainer, vital);
        userProcessContainer.add("AddEncounterJPanel", vvjp);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
      
    }//GEN-LAST:event_btnvitalActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed

        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
      
      
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnSearch1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearch1ActionPerformed
         
         
        AddVitalsJPanel avjp = new AddVitalsJPanel(userProcessContainer, vital, person);
        userProcessContainer.add("AddEncounterJPanel", avjp);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
        
        
      
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSearch1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnCreate;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnSearch1;
    private javax.swing.JButton btnView;
    private javax.swing.JButton btnvital;
    private javax.swing.JTable encounterusertable;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblhealth;
    // End of variables declaration//GEN-END:variables

    private void populateEncounterTable() {

        DefaultTableModel model= (DefaultTableModel) encounterusertable.getModel();
         model.setRowCount(0);
        
       
        for(Encounter e : encHistory.getHistory())
              {
             
           
            Object[] row=new Object[2];
            row[0]=e;
            row[1]=e.getEnc();
           
          
            model.addRow(row);
      
             }

    }

   
    }

