/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package uiAdmin;

import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import model.Encounter;
import model.Person;
import model.VitalSigns;

/**
 *
 * @author krishnamayavat
 */
public class ViewEncounterJPanel extends javax.swing.JPanel {
     
    private JPanel userProcessContainer;
    private Person person;
    
   

    ViewEncounterJPanel(JPanel upc, Person p) {
        
        initComponents();
        userProcessContainer = upc;
        person = p;
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnback3 = new javax.swing.JButton();
        lblencounter = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        encountertable = new javax.swing.JTable();
        btnviewvitals = new javax.swing.JButton();

        btnback3.setText("<< back");
        btnback3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnback3ActionPerformed(evt);
            }
        });

        lblencounter.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        lblencounter.setText("Encounter Details");

        encountertable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "HealthID", "Name", "LastVisitDate", "Encounter No."
            }
        ));
        jScrollPane1.setViewportView(encountertable);

        btnviewvitals.setText("View Vitals");
        btnviewvitals.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnviewvitalsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(btnback3)
                        .addGap(112, 112, 112)
                        .addComponent(lblencounter, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 541, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(261, 261, 261)
                        .addComponent(btnviewvitals)))
                .addContainerGap(72, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnback3)
                    .addComponent(lblencounter, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(btnviewvitals)
                .addContainerGap(126, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnback3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnback3ActionPerformed


 userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
        // TODO add your handling code here:
    }//GEN-LAST:event_btnback3ActionPerformed

    private void btnviewvitalsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnviewvitalsActionPerformed
          int row = encountertable.getSelectedRow();
        if(row<0){
            JOptionPane.showMessageDialog(null, "Please select a row!!", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        VitalSigns v  = (VitalSigns)encountertable.getValueAt(row,0);
        ViewVitalsJPanel vv = new ViewVitalsJPanel(userProcessContainer, v);
        userProcessContainer.add("ViewVitals", vv);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
        
        
        
        
        
        // TODO add your handling code here:
    }//GEN-LAST:event_btnviewvitalsActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnback3;
    private javax.swing.JButton btnviewvitals;
    private javax.swing.JTable encountertable;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblencounter;
    // End of variables declaration//GEN-END:variables
}
